version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - run: echo "time to deploy!"
      
workflows:
  deploy:
    jobs:
      - deploy
